name: Deploy to EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: SSH into EC2 instance and deploy
        uses: easingthemes/ssh-deploy@v2
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ubuntu
          REMOTE_PORT: ${{ secrets.SERVER_PORT }}
          SOURCE: build/*
          TARGET: /var/www/html/my-react-app/build/

      - name: Remove existing contents of /var/www/html/my-react-app/build/
        run: ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@${{ secrets.EC2_HOST }} 'rm -rf /var/www/html/my-react-app/build/*'

      - name: Copy new contents to /var/www/html/my-react-app/build/
        run: scp -i ${{ secrets.SSH_PRIVATE_KEY }} -r build/* ubuntu@${{ secrets.EC2_HOST }}:/var/www/html/my-react-app/build/

      - name: Restart Nginx
        run: ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@${{ secrets.EC2_HOST }} 'sudo service nginx restart'