name: Deploy to EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy to EC2
        run: |
          sudo rsync -avz --delete build/ ubuntu@${{ secrets.EC2_HOST }}:/var/www/html/my-react-app/build/
          ssh ubuntu@${{ secrets.EC2_HOST }} 'sudo service nginx restart'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
