name: Deploy to EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: SSH into EC2 instance and deploy
        uses: easingthemes/ssh-deploy@v2
        with:
          server: ${{ secrets.EC2_HOST }}
          username: ubuntu
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: build/*
          target: /var/www/html/my-react-app/build/